### ISSUE TITLE
https://github.com/microsoft/ProjectReunion/issues/16     Needs your attention.  👋👋👋👋👋👋

### ISSUE THREAD

**Issue by 77376** [wjk/CodelabsProject#1]
https://github.com/microsoft/ProjectReunion/issues/16

**Comment by wjk** [comment]
I don’t know why you opened this issue here. I am fully aware of the issues I opened in Project Reunion. I do not see anything in microsoft/ProjectReunion#16 that requires my immediate attention. Please don’t create issues in unrelated repositories to draw my attention to other issues. I am subscribed to all issues that merit my attention, and I am notified automatically of any discussion there. I am now locking this thread as off-topic.
